version: '3.8'
services:
  bot:
    build: .
    env_file: 
      - .env
    volumes:
      - .:/app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    command: python -m bot.main
